### ISSUE TITLE
Failing to backport because of merge conflicts should mark the github action step in error

### ISSUE THREAD

**Issue by sarod** [sqren/backport-github-action#33]
Hi,

I followed the setup described in the [README ](https://github.com/sqren/backport-github-action#readme).

When the backport fails because of merge conflicts the action logs the following JSON object:
```JSON
{
  "status": "success",
  "commits": [
    {
      "author": {
        "name": "Sebastien Arod",
        "email": "sebastien.arod@xxx.com"
      },
      "sourceCommit": {          
        "committedDate": "2022-05-20T15:08:34Z",
        "message": "xxx.",
        "sha": "dbdcace0fde6e50c46c4b929b3500e8b2aae8cc4"
      },
      "sourcePullRequest": {
        "number": 784,
        "url": "https://github.com/xxx/xxx/pull/784",
        "mergeCommit": {
          "message": "xxx.",
          "sha": "dbdcace0fde6e50c46c4b929b3500e8b2aae8cc4"
        }
      },
      "sourceBranch": "master",
      "expectedTargetPullRequests": [
        {
          "branch": "V5_3",
          "state": "NOT_CREATED"
        }
      ]
    }
  ],
  "results": [
    {
      "targetBranch": "V5_3",
      "status": "handled-error",
      "error": {
        "name": "BackportError",
        "errorContext": {
          "code": "merge-conflict-exception",
          "commitsWithoutBackports": [],
          "conflictingFiles": [
            "xxx.xxx"
          ]
        }
      }
    }
  ]
}
```

The `results` property part clearly indicate that there was some merge-conflict-exception but the global `status` is success and the step is considered successful. 

Is this the expected behavior? I would have expected a failed backport to fail the step.

**Comment by sqren** [comment]
> Is this the expected behavior? I would have expected a failed backport to fail the step.

This is somewhat expected behaviour. It's not set in stone but my intention is to only mark operational failures as "failed". This way an ops person can verify whether the github action is performing as expected or not by monitoring the failure rate.

If merge conflicts are marked as failure rate it becomes very hard to spot if there are operational failures (backport tool crashing for one reason or the other).

I'd love if I it was possible to mark a job with other states than simply "success" and "failure" but it doesn't look like it.

**Comment by sarod** [comment]
That makes sense. Thanks!

**Comment by sqren** [comment]
Closing for now. Feel free to comment if this comes up again

**Comment by vcidst** [comment]
Is it possible that pull requests with merge conflicts continue to be success but the structured output gives an indication that it contains a merge conflicts so a manual intervention can be made to fix it? We recently had an incident where a backport pull request with merge conflicts was merged. We can add a step in the workflow to check for merge conflicts but it would be nicer if this information is available from this action
